[SETTINGS]

; Hey look, a gen-u-ine .ini file for you to play with!  Messing with these settings will probably break stuff, but
; I assume that's why you're here in the first place.
;whether dusk has already run or not
firstrun = 1

;amount of pixelization to use
pixel = 3

; limited palette
colorfilter = 0

; bilinear filtering
bfilter = 0

; light bloom
bloom = 0

; lens flares
flares = 1

; camera animations
buck = 1

; weapon bob;
bob = 1

; always run toggle
alwaysrun = 1

; mouse inversion
inverty = 0

; mouse sensitivity
mousesensitivity = 0.0565

; saturation
saturation = 0

; brightness
brightness = 0

; contrast
contrast = 0

; hue
hue = 0

; game red tint
rtint = 255

; game green tint
gtint = 255

; game blue tint
btint = 255

; field of view
fov = 110

; toggle crouch or hold to crouch
crouchtoggle = 0

; fullscreen mode
fullscreen = 1

; vsync
vsync = 0

; screen x resolution
xres = 2560

; screen y resolution
yres = 1440

; crosshair red tint
crtint = 0

; crosshair green tint
cgtint = 255

; crosshair blue tint
cbtint = 0

; crosshair alpha
catint = 255

;crosshair style
crosshairstyle = 10

; ui on or off
uitoggle = 1

; master volume
mastervolume = 1.0

; music volume
musicvolume = 0.9

; amount of autoaim
autoaim = 0

; weapon size
weaponsize = 1.0

; autoswitch weapon on pickup
autoswitch = 0

; crosshair based on weapon
crossbasedonweapon = 1

; crosshair size
crosshairsize = 1.09736

; framerate limit. -1 is uncapped
framelock = -1

; reverse mouse wheel selection
mousewheelflip = 0

; use Descent-esque 6DGOF controls for swimming (the superior option for cool ppl)
6dgofSwimming = 1

; if 0, vertical look unlock is disabled
unlockedaxis = 1

; low spec mode for weak computers
lowspec = 0

; toggle controller on or off
controllertoggle = 0

; controller preset
controllerpreset = 0

; hud type
hud = 0

; auto hop
autohop = 0

; auto climb
autoclimb = 0

; subtitles
subtitles = 0

; language
language = 0
enableweaponwheel = 0
lookdeadzone = 0.2
movedeadzone = 0.2

[CONTROLS]
forward = E
backward = D
left = S
right = F
jump = Space
crouch = LeftControl
walk = LeftShift
fire = Mouse0
zoom = Mouse1
flashlight = Mouse2
flip = T
use = G
sickles = Alpha1
pistol = Alpha2
shotgun = Alpha4
super_shotgun = X
assault_rifle = C
hunting_rifle = W
crossbow = Q
mortar = R
riveter = V
cigar = Y
holster = H
last_used_weapon = Mouse3
quick_melee = Mouse4
toggle_stats = Tab
record_time = Slash
quick_save = F6
quick_load = F9

